---
  - name: Shell Examples
     hosts: HAProxy
     tasks:

    - name: Check Date with Shell command
      shell:
         "date"
      register: datecmd
      tags: datecmd

    - debug: msg="{{datecmd.stdout}}"
